#pragma once

#include <iostream>
#include <vector>
#include <map>

namespace factorio {

	inline std::vector<std::string> recipe_category = {
		"advanced-crafting",
		"basic-crafting",
		"centrifuging",
		"chemistry",
		"crafting",
		"crafting-with-fluid",
		"oil-processing",
		"rocket-building",
		"smelting"
	};

	inline std::vector<std::string> item_subgroup = {
		"ammo",
		"armor",
		"barrel",
		"belt",
		"belt-explosions",
		"belt-remnants",
		"campaign-explosions",
		"capsule",
		"capsule-explosions",
		"circuit-network",
		"circuit-network-explosions",
		"circuit-network-remnants",
		"cliffs",
		"corpses",
		"creatures",
		"decorative-explosions",
		"defensive-structure",
		"defensive-structure-explosions",
		"defensive-structure-remnants",
		"empty-barrel",
		"enemies",
		"energy",
		"energy-explosions",
		"energy-pipe-distribution",
		"energy-pipe-distribution-explosions",
		"energy-pipe-distribution-remnants",
		"energy-remnants",
		"equipment",
		"explosions",
		"extraction-machine",
		"extraction-machine-explosions",
		"extraction-machine-remnants",
		"fill-barrel",
		"fluid",
		"fluid-recipes",
		"generic-remnants",
		"grass",
		"ground-explosions",
		"gun",
		"gun-explosions",
		"hit-effects",
		"inserter",
		"inserter-explosions",
		"inserter-remnants",
		"intermediate-product",
		"logistic-network",
		"logistic-network-explosions",
		"logistic-network-remnants",
		"military-equipment",
		"module",
		"module-explosions",
		"other",
		"particles",
		"production-machine",
		"production-machine-explosions",
		"production-machine-remnants",
		"raw-material",
		"raw-resource",
		"remnants",
		"rock-explosions",
		"science-pack",
		"scorchmarks",
		"smelting-machine",
		"smelting-machine-explosions",
		"smelting-machine-remnants",
		"space-related",
		"storage",
		"storage-explosions",
		"storage-remnants",
		"terrain",
		"tool",
		"train-transport",
		"train-transport-explosions",
		"train-transport-remnants",
		"transport",
		"transport-explosions",
		"transport-remnants",
		"tree-explosions",
		"trees",
		"virtual-signal",
		"virtual-signal-color",
		"virtual-signal-letter",
		"virtual-signal-number",
		"virtual-signal-special"
	};

	/*inline std::vector<std::string> recipe_category = {

	};*/
}